name: CD
on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devops-test-web

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
          
      - name: Login to GitHub Packages Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
          cache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max            

# add token    
  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: build

    steps:    
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout Gitops Repository
        uses: actions/checkout@v2
        with:
          repository: kakaocloudschool/git-ops-test-web
          ref: main          
          token: ${{ secrets.ACTION_TOKEN }}
          path: git-ops-test-web

      - name: Update Kubernetes resources
        run: |
          cd git-ops-test-web/release
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
          cat kustomization.yaml
      - name: Commit files
        run: |
          cd git-ops-test-web
          git config --global user.email "kakaocloud-github-actions@github.com"
          git config --global user.name "kakaocloud-github-actions"
          git commit -am "[Devops] Change Image "
          git push -u origin main
          
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
