name: CD
on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: harbor.192.168.50.101.nip.io/k8s/devops-test-web

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3      
          
      - name: before_install
        run: |
          set -x
          sudo mkdir -p /etc/docker/
          sudo mkdir -p ~/.docker/
          sudo chmod 777 ~/.docker/
          sudo chmod 777 /etc/docker/
          echo '${{ secrets.REPO_CA }}' | sudo tee ~/ca.crt
          sudo cp ~/ca.crt /etc/ssl/certs/
          sudo cp ~/ca.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
          echo '${{ secrets.HARBOR_LOGIN_CONFIG }}' | sudo tee ~/.docker/config.json
          echo '{"insecure-registries" : ["harbor.192.168.50.101.nip.io"]}' | sudo tee /etc/docker/daemon.json

      - name: Set up Docker Context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders        
          
      - name: Login to GitHub Packages Container Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.192.168.50.101.nip.io
          username: ${{ secrets.HARBOR_ID }}
          password: ${{ secrets.HARBOR_PW }}
          
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
          cache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max            
     

# add token    
  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: build

    steps:    
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout Gitops Repository
        uses: actions/checkout@v2
        with:
          repository: kakaocloudschool/git-ops-test-web
          ref: main          
          token: ${{ secrets.ACTION_TOKEN }}
          path: git-ops-test-web

      - name: Update Kubernetes resources
        run: |
          cd git-ops-test-web/release
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
          cat kustomization.yaml
      - name: Commit files
        run: |
          cd git-ops-test-web
          git config --global user.email "kakaocloud-github-actions@github.com"
          git config --global user.name "kakaocloud-github-actions"
          git commit -am "[Devops] Change Image "
          git push -u origin main
          
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
