name: CI

on:
#   push:
#     branches:
#       - main
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux, x64]

    strategy:
      fail-fast: true
      matrix:
        httpd: ['latest']
      
    name: httpd ${{ matrix.httpd }}

    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3

    -
      name: Serve Files
      uses: Eun/http-server-action@v1
      with:
        directory: ${{ github.workspace }}/src
        port: 8080
        no-cache: false
        index-files: |
          ["index.html", "index.htm"]
        allowed-methods: |
          ["GET", "HEAD"]
        content-types: |
          {
            "appcache": "text/cache-manifest",
            "css": "text/css",
            "gif": "image/gif",
            "html": "text/html",
            "ico": "image/x-icon",
            "jpeg": "image/jpeg",
            "jpg": "image/jpeg",
            "js": "text/javascript",
            "json": "application/json",
            "png": "image/png",
            "txt": "text/plain",
            "xml": "text/xml"
          }
    -
      run: curl -vvvv http://localhost:8080/index.html

    -
      name: Module Testing
      run: echo Testing
    
    - name: Code Style Check
      run: echo "Style Checking by Sonarqube"

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
